name: Build and Generate Sitemap and Push Changes

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  build-and-generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }} # Use the PAT for checkout

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Generate Sitemap
        run: npm run postbuild

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Oliver Wolfson'
          git config --global user.email 'owolfdev@gmail.com'
          git add -A
          git commit -m "Update sitemap"
          git push
